### ISSUE TITLE
你好，请教下你的sx1268的代码是否可以移植到安卓系统？

### ISSUE THREAD

**Issue by 1282925159** [YukiWorkshop/sx128x_linux_driver#1]
你好，现在在安卓上调试sx1268这颗芯片，想问下你的代码能否移植到安卓上，因为刚接触驱动这行很多东西都没碰到过，希望大神能指点一二，谢谢！

**Comment by ClassicOldSong** [comment]
中文可用
没太能理解您想用英文表达的意思，可以直接使用中文沟通

**Comment by 1282925159** [comment]
你好，方便加下你的微信吗？

**Comment by ReimuNotMoe** [comment]
> 你好，方便加下你的微信吗？

不好意思，我平时不使用微信。

只要是基于Linux系统且启用了SPI和GPIO的用户态驱动（有`/dev/spidevX.X`和`/dev/gpiochipX`）就能用。

本项目为LGPLv3授权，您可以用于商业产品，但您必须在您的商业产品中（比如在“关于”窗口内）说明您使用了这个项目。

我们是一家技术公司，如果您需要技术支持（此时可使用微信），我们也可以付费提供。

**Comment by 1282925159** [comment]
你们怎么收费？

**Comment by ReimuNotMoe** [comment]
> 你们怎么收费？

您可以先整理出一份需求文档，并附上您的联系方式，然后发送到邮箱 `reimu@sudomaker.com`。
